// Copyright (c) 2025-2026 Continuum Identity SAS. All rights reserved.
// Licensed under the Business Source License 1.1. See LICENSE for details.
/**
 * Outgoing port for verification receipt storage.
 * A receipt is a one-time token generated by VerifyProofUseCase on success,
 * which IssueTokenUseCase must consume to create a cryptographic binding
 * between proof verification and token issuance.
 *
 * Each receipt is bound to a specific clientIdentifier, preventing one client
 * from using another client's verification receipt.
 */
export interface VerificationReceiptStore {
  /**
   * Stores a receipt binding a receiptId to a clientIdentifier.
   */
  store(receiptId: string, clientIdentifier: string): Promise<void>;

  /**
   * Atomically checks if the receipt exists and consumes it.
   * Returns the clientIdentifier if the receipt was successfully consumed.
   * Returns null if the receipt does not exist or was already consumed.
   */
  consume(receiptId: string): Promise<string | null>;
}
